spring:
  profiles:
    active: dev

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db_stu?serverTimezone=UTC
    username: root
    password: 123456

  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    show-sql: true


  http:
  servlet:
    multipart:
      enabled: true
      max-file-size: 200MB
      max-request-size: 200MB